name: cev_2ddoc_reader
description: Lecteur et authentificateur de documents CEV 2D-Doc
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Scanner caméra (Data Matrix + QR Code)
  mobile_scanner: ^5.1.1

  # Cryptographie ECDSA
  pointycastle: ^3.9.1

  # Encodage / utilitaires
  convert: ^3.1.1

  # UI Material 3
  google_fonts: ^6.2.1

  # Icônes
  cupertino_icons: ^1.0.8
  flutter_animate: ^4.5.2
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icones/